#!/usr/bin/env sh

. "$SCRIPTS/tmux.sh"
. "$SCRIPTS/book.sh"
. "$SCRIPTS/autoswitch_env.sh"
. "$SCRIPTS/gh.sh"
. "$SCRIPTS/nightlight.sh"
. "$SCRIPTS/theme_switcher.sh"
. "$SCRIPTS/powermenu.sh"
. "$SCRIPTS/cht.sh"
. "$SCRIPTS/history.sh"
. "$SCRIPTS/arch_setup.sh"
. "$SCRIPTS/rename_docs.sh"
. "$SCRIPTS/organize.sh"
. "$SCRIPTS/auto-commiter.sh"
. "$SCRIPTS/notes.sh"
